all: ex00 ex01 ex02

ex00:
	@echo "\n\033[32mex00 \033[0m"
	@go run ex00/cmd/main.go
	@echo "\n\033[32mtest for ex00 \033[0m"
	@go test -v ex00/getelement_test/getelement_test.go

ex01:
	@echo "\n\033[32mex01 \033[0m"
	@go run ex01/cmd/main.go

ex02:
	@echo "\n\033[32mex02 \033[0m"
	@go run ex02/cmd/main.go

.PHONY: ex00 ex01 ex02